### ISSUE TITLE
Module object has no attribute 'Api'

### ISSUE THREAD

**Issue by darkelement1987** [samarudge/twdlt#1]
Sorry for posting here but i can't find something to contact you, im getting this error when launching your app:

`c:\PokemonGo-Map-3.1.0\Tools\twdlt-master>twdlt` --config=config.json
Traceback (most recent call last):
  File "C:\Python27\Scripts\twdlt-script.py", line 11, in <module>
    load_entry_point('twdlt', 'console_scripts', 'twdlt')()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 275, in cli
    d.run()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 132, in run
    self.api()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 64, in api
    self.t = twitter.Api(
AttributeError: 'module' object has no attribute 'Api'

Has this something to do with me hitting my daily status limit?

edit: no more limit, still the same error :(

**Comment by darkelement1987** [comment]
Allright i've triedt pip install python-twitter --upgrade and now that's fine but im stuck at the next error:

c:\PokemonGo-Map-3.1.0\Tools\twdlt-master>twdlt --config=config.json
Traceback (most recent call last):
  File "C:\Python27\Scripts\twdlt-script.py", line 11, in <module>
    load_entry_point('twdlt', 'console_scripts', 'twdlt')()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 275, in cli
    d.run()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 132, in run
    self.api()
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 73, in api
    self.rateWait('verify')
  File "c:\pokemongo-map-3.1.0\tools\twdlt-master\src\twdlt\twdlt__init__.py", line 92, in rateWait
    json = self.t._FetchUrl(url, no_cache=True)
AttributeError: 'Api' object has no attribute '_FetchUrl'
